export default {
  authorizing: false,
  registring: false,
  gettingUsers: false,
  gettingUserInfo: false,
  gettingTransactions: false,
  creatingTransaction: false,
  requestError: null,
  authToken: null,
  userInfo: null,
  transactions: [],
  users: [],
  newTransaction: { user: null, amount: 0 },
  createdTransaction: {},
  newUser: null,
}
